final class e {
	
	static int anInt_a;
	static int[][] ints_b;
	static ob duelStake = rf.a(40, ":duelstake:");
	static int anInt_d;
	static int e = 0;
	static int f;
	static int anInt_g;
	static of of_h;
	static ob i;
	static ob j;
	static ob k = rf.a(40, "<col=ffffff> )4 ");
	static int anInt_l;
	private static ob ob_m = rf.a(40, "Select");
	static ob ob_n = rf.a(40, "jolt");
	
	static void a(int var0) {
		int dummy = client.anInt_wb;
		
		try {
			lb.nb = true;
			qc.D = true;
			ff.db = 0L;
			++f;
			anInt_l = 0;
			jd.i = 0;
			qi.u = 0;
			cc.F = 0;
			jf.W = 0;
			jf.Y = 0;
			ca.tb = 0;
			nf.bb = 0;
			ki.a = 0;
			ee.f = 0;
			ff.gb = 0;
			ge.W = 0;
			client.anInt_vb = 0;
			o.a = 0;
			lh.anInt_nb = 0;
			ie.J = 0;
			vg.bb = 0;
			df.x = 0;
			ef.jb = 0;
			l.q = 0;
			ee.j = 0;
			gb.Z = 0;
			na.I = 0;
			ji.x = 0;
			h.u = 0;
			ob.J = 0;
			ve.j = 0;
			og.bb = 0;
			gi.B = 0;
			g.gb = 0;
			jd.o = 0;
			vc.i = 0;
			client.anInt_jb = 0;
			rc.w = 0;
			bc.eb = 0;
			md.v = 0;
			ug.p = 0;
			ob.d = 0;
			h.ub = 0;
			ke.ob = 0;
			wc.D = 0;
			ob.f = 0;
			af.A = 0;
			g.cb = 0;
			dh.g = 0;
			jf.ab = 0;
			ja.v = 0;
			ji.o = 0;
			pg.S = 0;
			jc.R = 0;
			hi.j = 0;
			af.M = 0;
			da.P = 0;
			hc.v = 0;
			ja.anInt_l = 0;
			bc.T = 0;
			b.db = 0;
			ra.n = 0;
			m.o = 0;
			lf.K = 0;
			fh.k = 0;
			pe.f = 0;
			fc.db = 0;
			na.w = 0;
			ii.u = 0;
			ph.r = 0;
			qa.f = 0;
			pa.j = 0;
			sh.a = 0;
			pa.c = 0;
			ee.e = 0;
			client.R = 0;
			ea.V = 0;
			dd.e = 0;
			da.cb = 0;
			hi.d = 0;
			rf.E = 0;
			og.A = 0;
			fc.Nb = 0;
			ra.Cc = 0;
			h.Cb = 0;
			vc.j = 0;
			h.eb = 0;
			r.cb = 0;
			cf.S = 0;
			d.Q = 0;
			ri.c = 0;
			s.S = 0;
			pe.anInt_g = 0;
			me.k = 0;
			ra.p = 0;
			ud.Nb = 0;
			th.cb = 0;
			qh.f = 0;
			ib.e = 0;
			ch.T = 0;
			ia.Z = 0;
			ii.w = 0;
			q.ib = 0;
			qi.m = 0;
			mc.w = 0;
			lh.sb = 0;
			vf.C = 0;
			c.X = 0;
			pc.i = 0;
			na.anInt_g = 0;
			ja.c = 0;
			ai.G = 0;
			qb.F = 0;
			og.zb = 0;
			ff.ob = 0;
			ob.g = 0;
			qd.G = 0;
			ea.Z = 0;
			hi.A = 0;
			md.q = 0;
			ie.x = 0;
			og.Ab = 0;
			fb.bb = 0;
			wc.w = 0;
			mi.V = 0;
			pi.r = 0;
			nb.jc = 0;
			ei.vb = 0;
			og.W = 0;
			og.y = 0;
			ci.r = 0;
			eb.R = 0;
			ri.g = 0;
			og.nb = 0;
			na.anInt_a = 0;
			od.cb = 0;
			kh.D = 0;
			rg.A = 0;
			jc.cb = 0;
			vc.h = 0;
			ce.N = 0;
			ii.r = 0;
			hf.f = 0;
			h.xb = 0;
			ji.r = 0;
			mc.y = 0;
			se.m = 0;
			ob.e = 0;
			wf.a = 0;
			mc.v = 0;
			ja.m = 0;
			wd.h = 0;
			jd.p = 0;
			bc.cb = 0;
			lg.anInt_a = 0;
			ub.a = 0;
			ea.Y = 0;
			client.anInt_fb = 0;
			sb.lb = 0;
			og.D = 0;
			h.L = 0;
			le.S = 0;
			ta.ab = 0;
			jg.j = 0;
			pe.Y = 0;
			pg.T = 0;
			ac.E = 0;
			vg.T = 0;
			ef.mb = 0;
			dd.d = 0;
			cc.Q = 0;
			ob.q = 0;
			na.E = 0;
			be.d = 0;
			client.anInt_eb = 0;
			q.cb = 0;
			aa.L = 0;
			lh.bb = 0;
			vf.B = 0;
			fb.db = 0;
			oe.h = 0;
			fb.Y = 0;
			ra.O = 0;
			rd.F = 0;
			og.M = 0;
			og.B = 0;
			af.anInt_p = 0;
			ob.H = 0;
			lg.c = 0;
			pe.L = 0;
			og.rb = 0;
			sh.c = 0;
			vg.ab = 0;
			ba.anInt_b = 0;
			se.o = 0;
			qa.x = 0;
			b.cb = 0;
			ai.L = 0;
			ei.Db = 0;
			hi.b = 0;
			kg.h = 0;
			aa.I = 0;
			pd.o = 0;
			client.anInt_pb = 0;
			na.L = 0;
			ih.h = 0;
			md.o = 0;
			ei.db = 0;
			ja.n = 0;
			n.a = 0;
			fc.Lb = 0;
			aa.D = 0;
			pb.b = 0;
			d.H = 0;
			mf.Y = 0;
			od.fb = 0;
			vd.anInt_a = 0;
			kf.a = 0;
			na.i = 0;
			ca.anint_wb = 0;
			o.g = 0;
			ff.hb = 0;
			ii.y = 0;
			hc.g = 0;
			ca.pb = 0;
			ob.D = 0;
			tf.k = 0;
			qa.b = 0;
			tf.c = 0;
			dc.i = 0;
			vb.j = 0;
			tb.n = 0;
			cf.eb = 0;
			tg.n = 0;
			nc.f = 0;
			na.x = 0;
			og.S = 0;
			tb.g = 0;
			wg.ib = 0;
			h.wb = 0;
			ja.s = 0;
			h.rb = 0;
			pb.c = 0;
			ta.O = 0;
			ud.fb = 0;
			hc.m = 0;
			lg.r = 0;
			ub.e = 0;
			ge.L = 0;
			bg.k = 0;
			na.anInt_b = 0;
			mf.fb = 0;
			bf.jb = 0;
			ch.X = 0;
			ua.g = 0;
			gh.fb = 0;
			qf.Q = 0;
			n.j = 0;
			ge.E = 0;
			pe.anInt_c = 0;
			n.f = 0;
			rg.x = 0;
			pe.b = 0;
			ae.Vb = 0;
			gf.t = 0;
			id.o = 0;
			f = 0;
			od.W = 0;
			ei.anInt_nb = 0;
			wg.eb = 0;
			lf.I = 0;
			ri.o = 0;
			ri.l = 0;
			aa.G = 0;
			og.P = 0;
			ed.f = 0;
			wg.T = 0;
			ba.c = 0;
			ja.anInt_e = 0;
			gh.ib = 0;
			lg.k = 0;
			ra.anInt_sb = 0;
			bh.b = 0;
			jc.Y = 0;
			jd.n = 0;
			og.anInt_lb = 0;
			oc.a = 0;
			client.anInt_ab = 0;
			qa.a = 0;
			bg.anInt_l = 0;
			cf.fb = 0;
			le.R = 0;
			md.b = 0;
			sh.g = 0;
			ta.Q = 0;
			df.q = 0;
			uc.S = 0;
			id.w = 0;
			client.anInt_ob = 0;
			mc.J = 0;
			ob.n = 0;
			ja.w = 0;
			ge.H = 0;
			li.o = 0;
			ie.A = 0;
			mf.W = 0;
			wc.H = 0;
			ka.G = 0;
			qg.h = 0;
			uc.hb = 0;
			na.z = 0;
			ei.ib = 0;
			di.e = 0;
			pc.b = 0;
			hh.H = 0;
			a.b = 0;
			jg.g = 0;
			qe.m = 0;
			pe.H = 0;
			ta.V = 0;
			ia.V = 0;
			c.R = 0;
			og.xb = 0;
			ag.d = 0;
			ka.y = 0;
			ae.anInt_bc = 0;
			h.vb = 0;
			client.anInt_nb = 0;
			tc.N = 0;
			uc.gb = 0;
			ge.J = 0;
			gf.C = 0;
			lh.X = 0;
			rf.anInt_o = 0;
			d.L = 0;
			pa.g = 0;
			bc.bb = 0;
			lg.i = 0;
			s.eb = 0;
			ga.i = 0;
			bf.db = 0;
			ii.s = 0;
			h.F = 0;
			ae.Ub = 0;
			r.V = 0;
			ob.L = 0;
			ni.fb = 0;
			be.e = 0;
			jd.g = 0;
			md.d = 0;
			ni.kb = 0;
			og.X = 0;
			tc.D = 0;
			mc.K = 0;
			hi.e = 0;
			ih.r = 0;
			eb.bb = 0;
			wb.T = 0;
			af.C = 0;
			bf.bb = 0;
			ra.Dc = 0;
			fc.G = 0;
			li.anInt_m = 0;
			wa.t = 0;
			lf.H = 0;
			ue.ab = 0;
			ia.U = 0;
			ri.e = 0;
			uc.W = 0;
			ei.Bb = 0;
			hc.h = 0;
			sh.h = 0;
			ie.H = 0;
			c.W = 0;
			ad.R = 0;
			na.anInt_t = 0;
			je.V = 0;
			pg.W = 0;
			hf.c = 0;
			df.y = 0;
			g.W = 0;
			lg.f = 0;
			pi.n = 0;
			ud.V = 0;
			fh.l = 0;
			kd.cb = 0;
			ee.d = 0;
			sc.a = 0;
			ph.l = 0;
			lf.B = 0;
			qb.D = 0;
			n.m = 0;
			gf.o = 0;
			g.L = 0;
			jd.f = 0;
			be.c = 0;
			pe.k = 0;
			mc.z = 0;
			va.g = 0;
			ge.Q = 0;
			ea.bb = 0;
			ii.anInt_v = 0;
			ce.E = 0;
			mc.I = 0;
			ni.ob = 0;
			kh.W = 0;
			hh.Q = 0;
			v.I = 0;
			qa.s = 0;
			nf.R = 0;
			mf.ab = 0;
			gi.A = 0;
			qf.s = 0;
			hi.s = 0;
			bd.E = 0;
			ob.b = 0;
			jd.m = 0;
			og.E = 0;
			sb.W = 0;
			vc.d = 0;
			og.Cb = 0;
			cd.j = 0;
			na.F = 0;
			pg.Y = 0;
			ca.ub = 0;
			ph.x = 0;
			qh.k = 0;
			ph.b = 0;
			ra.Z = 0;
			v.ub = 0;
			qh.g = 0;
			ih.B = 0;
			dh.j = 0;
			pe.G = 0;
			ic.db = 0;
			qa.u = 0;
			ie.s = 0;
			vf.r = 0;
			ei.S = 0;
			bc.Y = 0;
			ba.i = 0;
			ua.o = 0;
			ef.hb = 0;
			ra.Ib = 0;
			oe.d = 0;
			hf.u = 0;
			kf.m = 0;
			se.c = 0;
			kd.eb = 0;
			qa.r = 0;
			fc.Qb = 0;
			ug.y = 0;
			qb.O = 0;
			bi.g = 0;
			nf.fb = 0;
			og.Eb = 0;
			ae.Ob = 0;
			hc.l = 0;
			le.eb = 0;
			a.l = 0;
			vd.anInt_d = 0;
			bg.f = 0;
			rf.p = 0;
			b.W = 0;
			lg.m = 0;
			wg.kb = 0;
			ee.h = 0;
			tc.L = 0;
			d.J = 0;
			ve.o = 0;
			fc.Eb = 0;
			vg.R = 0;
			dg.vc = 0;
			ja.q = 0;
			md.y = 0;
			jb.R = 0;
			ad.X = 0;
			mf.Z = 0;
			n.c = 0;
			b.bb = 0;
			h.z = 0;
			na.J = 0;
			hc.t = 0;
			pe.A = 0;
			dg.Hc = 0;
			d.O = 0;
			ob.t = 0;
			vb.I = 0;
			h.bb = 0;
			bd.O = 0;
			pi.l = 0;
			re.F = 0;
			mc.C = 0;
			oh.I = 0;
			th.V = 0;
			mi.U = 0;
			cd.b = 0;
			hc.u = 0;
			ud.S = 0;
			ja.g = 0;
			bf.eb = 0;
			tf.a = 0;
			je.ab = 0;
			og.pb = 0;
			cc.S = 0;
			ua.k = 0;
			oe.i = 0;
			og.N = 0;
			mf.U = 0;
			g.eb = 0;
			gf.I = 0;
			af.anInt_q = 0;
			ei.R = 0;
			h.E = 0;
			dc.d = 0;
			dc.anInt_a = 0;
			client.W = 0;
			ge.Y = 0;
			og.V = 0;
			pi.g = 0;
			jc.hb = 0;
			og.r = 0;
			l.f = 0;
			ce.Q = 0;
			kd.fb = 0;
			ke.nb = 0;
			ai.pb = 0;
			og.tb = 0;
			ga.t = 0;
			ic.E = 0;
			pa.i = 0;
			bi.c = 0;
			ac.o = 0;
			hg.f = 0;
			client.U = 0;
			nc.anInt_e = 0;
			lb.sb = 0;
			h.y = 0;
			ac.A = 0;
			hc.p = 0;
			af.y = 0;
			og.ib = 0;
			ua.i = 0;
			li.j = 0;
			ce.fb = 0;
			og.z = 0;
			jg.l = 0;
			rd.I = 0;
			ag.h = 0;
			na.anInt_r = 0;
			ad.V = 0;
			pe.I = 0;
			hi.anInt_m = 0;
			rc.a = 0;
			wh.g = 0;
			ld.x = 0;
			ob.K = 0;
			q.gb = 0;
			nf.db = 0;
			m.E = 0;
			na.A = 0;
			ob.X = 0;
			s.Z = 0;
			ob.E = 0;
			mi.X = 0;
			tg.anInt_m = 0;
			wb.S = 0;
			si.bb = 0;
			h.ob = 0;
			sh.j = 0;
			ji.n = 0;
			aa.E = 0;
			eh.U = 0;
			eb.X = 0;
			lh.Z = 0;
			li.b = 0;
			h.B = 0;
			bh.h = 0;
			ob.ab = 0;
			m.n = 0;
			ea.W = 0;
			ob.R = 0;
			pg.U = 0;
			hh.I = 0;
			ob.y = 0;
			ob.k = 0;
			rd.E = 0;
			ph.n = 0;
			q.ab = 0;
			pe.M = 0;
			pe.z = 0;
			na.anInt_l = 0;
			vc.k = 0;
			jb.db = 0;
			af.x = 0;
			ig.a = 0;
			h.tb = 0;
			sh.n = 0;
			ae.Qb = 0;
			fg.d = 0;
			wc.I = 0;
			ei.E = 0;
			pe.S = 0;
			sb.db = 0;
			fc.Ab = 0;
			h.Z = 0;
			pc.j = 0;
			h.t = 0;
			h.yb = 0;
			ob.G = 0;
			ig.e = 0;
			ef.Z = 0;
			ud.db = 0;
			ih.u = 0;
			na.H = 0;
			pi.f = 0;
			sb.ib = 0;
			dg.Fc = 0;
			h.Y = 0;
			ob.Z = 0;
			l.l = 0;
			ke.anInt_ub = 0;
			ob.A = 0;
			lb.ob = 0;
			ob.O = 0;
			ah.c = 0;
			qa.t = 0;
			qa.y = 0;
			da.bb = 0;
			cc.L = 0;
			ac.D = 0;
			kg.l = 0;
			vf.u = 0;
			ce.I = 0;
			cf.T = 0;
			cf.db = 0;
			ei.I = 0;
			na.anInt_f = 0;
			nf.X = 0;
			pe.anInt_a = 0;
			ua.j = 0;
			ob.o = 0;
			dg.kc = 0;
			r.U = 0;
			hb.v = 0;
			c.bb = 0;
			kd.R = 0;
			bh.e = 0;
			pi.e = 0;
			gh.V = 0;
			og.O = 0;
			nb.lc = 0;
			ta.U = 0;
			di.a = 0;
			wd.m = 0;
			na.D = 0;
			hg.anInt_e = 0;
			gb.X = 0;
			ke.tb = 0;
			qc.w = 0;
			hh.N = 0;
			client.anInt_ib = 0;
			og.gb = 0;
			vd.j = 0;
			ve.q = 0;
			ai.vb = 0;
			ob.m = 0;
			gg.z = 0;
			fc.gb = 0;
			o.c = 0;
			ea.U = 0;
			ni.hb = 0;
			og.ob = 0;
			lg.t = 0;
			jc.T = 0;
			ee.a = 0;
			ca.yb = 0;
			ca.vb = 0;
			dh.b = 0;
			ue.W = 0;
			oh.Q = 0;
			wb.U = 0;
			ki.m = 0;
			pi.p = 0;
			ie.v = 0;
			ua.b = 0;
			ob.Q = 0;
			re.x = var0;
			ie.t = 0;
			m.y = 0;
			h.Eb = 0;
			vc.a = 0;
			kd.bb = 0;
			fb.W = 0;
			oc.c = 0;
			ni.ib = 0;
			sb.eb = 0;
			wh.c = 0;
			ob.N = 0;
			sf.j = 0;
			qh.b = 0;
			wg.S = 0;
			ja.o = 0;
			bh.j = 0;
			jg.m = 0;
			pe.P = 0;
			h.K = 0;
			nb.qc = 0;
			ca.Ob = 0;
			ic.bb = 0;
			li.f = 0;
			mc.A = 0;
			ja.E = 0;
			h.I = 0;
			fi.b = 0;
			h.D = 0;
			ug.o = 0;
			hh.K = 0;
			h.w = 0;
			od.X = 0;
			lb.yb = 0;
			rd.D = 0;
			ie.D = 0;
			vd.anInt_c = 0;
			vg.U = 0;
			g.Q = 0;
			sf.l = 0;
			og.U = 0;
			pe.N = 0;
			md.p = 0;
			qc.y = 0;
			na.p = 0;
			lg.w = 0;
			ca.eb = 0;
			jg.o = 0;
			ce.O = 0;
			sa.k = 0;
			fb.R = 0;
			nd.f = 0;
			h.Bb = 0;
			b.Z = 0;
			r.T = 0;
			hc.b = 0;
			ff.pb = 0;
			da.xb = 0;
			r.W = 0;
			qa.v = 0;
			nb.sc = 0;
			d.R = 0;
			la.anInt_s = 0;
			q.mb = 0;
			wg.Y = 0;
			oe.f = 0;
			og.K = 0;
			a.q = 0;
			ie.y = 0;
			va.k = 0;
			eb.W = 0;
			qc.z = 0;
			sh.i = 0;
			ve.m = 0;
			g.S = 0;
			be.k = 0;
			ug.r = 0;
			o.h = 0;
			gb.W = 0;
			hc.f = 0;
			na.k = 0;
			mg.k = 0;
			pe.B = 0;
			vg.V = 0;
			qb.J = 0;
			h.W = 0;
			lh.tb = 0;
			h.db = 0;
			ca.Jb = 0;
			me.e = 0;
			c.T = 0;
			fb.cb = 0;
			tb.a = 0;
			ef.anInt_nb = 0;
			mf.X = 0;
			af.G = 0;
			ug.t = 0;
			ra.Pb = 0;
			vf.t = 0;
			ga.s = 0;
			dg.tc = 0;
			rg.anInt_r = 0;
			pi.i = 0;
			ib.g = 0;
			jb.hb = 0;
			ki.o = 0;
			og.q = 0;
			ge.G = 0;
			na.j = 0;
			uc.fb = 0;
			h.T = 0;
			lg.g = 0;
			rf.anInt_s = 0;
			fc.L = 0;
			di.f = 0;
			ig.d = 0;
			n.e = 0;
			h.M = 0;
			nc.d = 0;
			ob.C = 0;
			li.d = 0;
			fc.pb = 0;
			qh.h = 0;
			tb.e = 0;
			hi.u = 0;
			bh.d = 0;
			ii.B = 0;
			bf.Z = 0;
			r.gb = 0;
			cd.f = 0;
			fb.T = 0;
			na.anInt_d = 0;
			la.w = 0;
			hi.x = 0;
			og.J = 0;
			cc.R = 0;
			ob.I = 0;
			gb.T = 0;
			ob.anInt_p = 0;
			ua.f = 0;
			tf.f = 0;
			qb.K = 0;
			fg.h = 0;
			jb.ab = 0;
			oh.R = 0;
			jg.r = 0;
			tg.j = 0;
			lh.hb = 0;
			pi.b = 0;
			ge.U = 0;
			ic.P = 0;
			hh.D = 0;
			pe.x = 0;
			ob.x = 0;
			jb.Y = 0;
			pe.J = 0;
			oc.e = 0;
			ii.t = 0;
			pe.h = 0;
			ng.D = 0;
			ra.Sb = 0;
			sb.R = 0;
			ei.pb = 0;
			pe.s = 0;
			od.bb = 0;
			ai.I = 0;
			hi.z = 0;
			se.g = 0;
			de.b = 0;
			ob.db = 0;
			ge.X = 0;
			oe.j = 0;
			ra.rb = 0;
			pe.j = 0;
			sa.i = 0;
			jb.X = 0;
			ie.B = 0;
			og.Gb = 0;
			bh.k = 0;
			sb.V = 0;
			rd.G = 0;
			oe.m = 0;
			fg.g = 0;
			ai.P = 0;
			ae.Nb = 0;
			bi.d = 0;
			ua.m = 0;
			dh.a = 0;
			ra.Cb = 0;
			oh.N = 0;
			pi.q = 0;
			md.t = 0;
			na.anInt_q = 0;
			client.Y = 0;
			id.C = 0;
			hb.o = 0;
			ae.fc = 0;
			re.E = 0;
			ab.i = 0;
			h.nb = 0;
			jb.kb = 0;
			ph.s = 0;
			kh.U = 0;
			h.J = 0;
			vg.Y = 0;
			vc.l = 0;
			tg.c = 0;
			tg.i = 0;
			od.R = 0;
			tc.O = 0;
			r.hb = 0;
			bg.anInt_e = 0;
			og.I = 0;
			ob.a = 0;
			hi.c = 0;
			hc.n = 0;
			h.ab = 0;
			ob.w = 0;
			da.ub = 0;
			dh.o = 0;
			vd.anInt_b = 0;
			og.L = 0;
			oc.l = 0;
			vc.b = 0;
			ra.g = 0;
			pc.anInt_e = 0;
			qe.j = 0;
			cf.ab = 0;
			na.y = 0;
			vf.v = 0;
			nd.d = 0;
			tc.M = 0;
			client.P = 0;
			ud.Cb = 0;
			af.L = 0;
			tg.f = 0;
			ie.C = 0;
			tc.K = 0;
			ei.bb = 0;
			ue.eb = 0;
			s.Y = 0;
			og.G = 0;
			lh.S = 0;
			ai.rb = 0;
			ob.i = 0;
			ve.h = 0;
			ra.fc = 0;
			bd.L = 0;
			da.sb = 0;
			q.R = 0;
			lh.lb = 0;
			h.Q = 0;
			ef.S = 0;
			kh.F = 0;
			lg.e = 0;
			qf.v = 0;
			oe.c = 0;
			qa.n = 0;
			fc.R = 0;
			og.T = 0;
			dh.c = 0;
			si.U = 0;
			ei.Q = 0;
			gb.Y = 0;
			qa.e = 0;
			pe.anInt_p = 0;
			vf.q = 0;
			eb.T = 0;
			ed.anInt_h = 0;
			ob.l = 0;
			wh.d = 0;
			ai.X = 0;
			uc.eb = 0;
			bi.h = 0;
			anInt_g = 0;
			pe.u = 0;
			qe.c = 0;
			fi.i = 0;
			q.X = 0;
			ob.F = 0;
			s.cb = 0;
			og.H = 0;
			gh.O = 0;
			qc.u = 0;
			hi.G = 0;
			hi.t = 0;
			ea.T = 0;
			a.g = 0;
			ih.D = 0;
			qc.s = 0;
			fg.f = 0;
			gg.m = 0;
			pa.f = 0;
			fh.g = 0;
			h.s = 0;
			ic.Q = 0;
			ed.b = 0;
			ua.q = 0;
			na.anInt_v = 0;
			fc.Sb = 0;
			hi.anInt_r = 0;
			gh.sb = 0;
			cc.M = 0;
			mc.F = 0;
			jc.V = 0;
			wb.W = 0;
			tf.g = 0;
			bc.X = 0;
			cd.g = 0;
			nf.Z = 0;
			hc.q = 0;
			c.V = 0;
			aa.J = 0;
			pc.c = 0;
			wg.X = 0;
			ue.cb = 0;
			ob.W = 0;
			og.p = 0;
			gh.qb = 0;
			qg.b = 0;
			wc.B = 0;
			ng.p = 0;
			og.vb = 0;
			af.J = 0;
			ic.F = 0;
			kh.K = 0;
			qa.c = 0;
			ob.B = 0;
			ae.Pb = 0;
			ob.z = 0;
			wg.Z = 0;
			dg.ic = 0;
			vg.cb = 0;
			ge.M = 0;
			vc.f = 0;
			og.C = 0;
			kg.c = 0;
			fc.tb = 0;
			gf.z = 0;
			af.anInt_r = 0;
			uc.Z = 0;
			og.sb = 0;
			oe.anInt_l = 0;
			fh.j = 0;
			s.ab = 0;
			ob.M = 0;
			hc.s = 0;
			tg.h = 0;
			h.x = 0;
			le.ib = 0;
			lb.vb = 0;
			ka.z = 0;
			hh.L = 0;
			je.db = 0;
			og.mb = 0;
			kh.M = 0;
			od.Z = 0;
			na.anInt_e = 0;
			df.o = 0;
			lg.b = 0;
			qd.K = 0;
			ce.ab = 0;
			lg.o = 0;
			na.B = 0;
			n.b = 0;
			ai.qb = 0;
			nf.cb = 0;
			nf.U = 0;
			ob.c = 0;
			h.S = 0;
			ja.t = 0;
			wc.z = 0;
			sb.kb = 0;
			ca.ob = 0;
			lg.n = 0;
			client.anInt_cb = 0;
			me.p = 0;
			tf.anInt_d = 0;
			pe.R = 0;
			ia.R = 0;
			l.anInt_e = 0;
			nf.gb = 0;
			ie.z = 0;
			og.Db = 0;
			nd.h = 0;
			na.anInt_h = 0;
			le.Y = 0;
			og.yb = 0;
			l.k = 0;
			gi.C = 0;
			ph.g = 0;
			nb.tc = 0;
			pi.j = 0;
			bf.ib = 0;
			ac.G = 0;
			th.ab = 0;
			ng.t = 0;
			da.U = 0;
			pe.D = 0;
			pe.C = 0;
			b.T = 0;
			di.h = 0;
			mc.D = 0;
			ig.f = 0;
			hi.g = 0;
			pe.t = 0;
			ac.F = 0;
			ei.M = 0;
			og.t = 0;
			a.o = 0;
			wg.gb = 0;
			nb.rc = 0;
			ag.m = 0;
			pg.X = 0;
			na.u = 0;
			bc.kb = 0;
			ua.l = 0;
			eh.R = 0;
			gb.bb = 0;
			jc.eb = 0;
			dh.f = 0;
			kg.n = 0;
			ai.bb = 0;
			bh.i = 0;
			ca.Db = 0;
			ce.L = 0;
			vg.W = 0;
			og.ab = 0;
			og.kb = 0;
			g.fb = 0;
			mg.e = 0;
			ud.qb = 0;
			qe.l = 0;
			ac.u = 0;
			r.bb = 0;
			ja.A = 0;
			lb.xb = 0;
			og.Y = 0;
			ra.oc = 0;
			l.i = 0;
			mg.j = 0;
			client.anInt_gb = 0;
			hb.p = 0;
			de.t = 0;
			ob.u = 0;
			oe.p = 0;
			lh.pb = 0;
			fh.m = 0;
			og.R = 0;
			h.O = 0;
			rg.y = 0;
			md.c = 0;
			lb.mb = 0;
			ab.d = 0;
			ca.Hb = 0;
			sc.h = 0;
			tg.l = 0;
			rf.B = 0;
			sf.c = 0;
			n.h = 0;
			client.anInt_ub = 0;
			pe.K = 0;
			sc.l = 0;
			af.H = 0;
			qa.q = 0;
			ce.X = 0;
			da.ob = 0;
			se.l = 0;
			le.Z = 0;
			jf.V = 0;
			af.anInt_o = 0;
			pg.ab = 0;
			ae.ec = 0;
			q.S = 0;
			bf.U = 0;
			lb.hb = 0;
			jh.i = 0;
			mc.B = 0;
			od.T = 0;
			ai.ub = 0;
			na.K = 0;
			ge.R = 0;
			af.w = 0;
			bc.nb = 0;
			uc.bb = 0;
			client.anInt_mb = 0;
			bi.b = 0;
			bd.F = 0;
			li.c = 0;
			wg.hb = 0;
			vd.anInt_e = 0;
			og.Fb = 0;
			na.anInt_s = 0;
			na.anInt_o = 0;
			ph.q = 0;
			th.Y = 0;
			dh.q = 0;
			le.W = 0;
			hi.n = 0;
			d.M = 0;
			hi.q = 0;
			og.wb = 0;
			ri.d = 0;
			pc.a = 0;
			va.c = 0;
			cc.N = 0;
			rg.anInt_q = 0;
			kd.ab = 0;
			qa.H = 0;
			qg.a = 0;
			m.anInt_q = 0;
			ra.Yb = 0;
			ua.p = 0;
			ph.w = 0;
			af.F = 0;
			eh.S = 0;
			ce.db = 0;
			pg.V = 0;
			rg.p = 0;
			eb.U = 0;
			pb.e = 0;
			ie.G = 0;
			m.A = 0;
			gi.anInt_v = 0;
			tb.o = 0;
			sb.T = 0;
			pe.y = 0;
			md.m = 0;
			df.B.x = 0;
			ff.R = 0;
			pa.b(3);
			ed.anInt_g = 0;
			kg.a = 0;
			tg.q = -1;
			af.P.pointer = 0;
			gf.F = -1;
			ff.ab = -1;
			ei.anInt_sb = 0;
			rd.O = -1;
			pg.packetBuffer.pointer = 0;
			int i = 0;
			/*if (dummy != 0) {
				int i1 = na.N;
				++i1;
				na.N = i1;
				ua.kis_a[i] = null;
				++i;
			}*/
			
			while (~i > ~ua.kis_a.length) {
				ua.kis_a[i] = null;
				++i;
			}
			
			le.X = false;
			si.S = 0;
			wa.b(0, -23383);
			for (int index = 0; index < 100; index++) {
				wf.l[index] = null;
			}
			wd.q = 0;
			ki.u = 0;
			g.O = false;
			se.b = 0;
			qg.c = -50 + (int) (Math.random() * 100.0D);
			se.e = 0;
			jg.h = (int) (Math.random() * 120.0D) + -60;
			ch.cb = 0;
			a.a = (int) (Math.random() * 110.0D) + -55;
			rh.t = -1;
			tf.n = 0;
			dh.k = 0;
			ve.anInt_l = 2047 & -10 + (int) (20.0D * Math.random());
			wc.p = -40 + (int) (Math.random() * 80.0D);
			lg.d = -20 + (int) (Math.random() * 30.0D);
			wg.db = 0;
			
			for (int index = 0; index < 2048; index++) {
				lg.j[index] = null;
				bc.lb[index] = null;
			}
			
			for (int index = 0; index < 32768; index++) {
				ai.M[index] = null;
			}
			
			le.T = lg.j[2047] = new dg();
			ci.u.c(99);
			nf.ib.c(-62);
			int i1 = 0;
			int id;
			int i2;
			re class_re;
			int i3;
			int i4;
			int i5;
			int i6;
			rd class_rd;
			if (/*dummy == 0 && */~i1 <= -5) {
				vg.X = new pi();
				ch.bb = 0;
				ii.o = 0;
				id = 0;
				if (/*dummy != 0 ||*/ wd.j > id) {
					while (wd.j > id) {
						class_rd = qd.a(false, id);
						if (class_rd != null && ~class_rd.H == -1) {
							ji.K[id] = 0;
							sa.c[id] = 0;
						}
						
						++id;
					}
				}
				
				i2 = 0;
				while (b.fb.length > i2) {
					b.fb[i2] = -1;
					++i2;
				}
				
				if (bg.h != -1) {//Pane id
					de.a(-3, bg.h);
				}
				
				class_re = (re) rd.J.b((byte) 117);
				while (class_re != null) {
					ba.a(class_re, var0 + 1, true);
					class_re = (re) rd.J.a((byte) -33);
				}
				
				bg.h = -1;
				rd.J = new md(8);
				sb.Z = null;
				si.S = 0;
				le.X = false;
				oe.g.a(new int[5], null, -1, 0, false);
				i3 = 0;
				if (/*dummy != 0 || */~i3 > -9) {
					do {
						gg.o[i3] = null;
						fh.c[i3] = false;
						++i3;
					} while (~i3 > -9);
				}
				
				sh.c(32);
				o.d = true;
				i4 = 0;
				while (~i4 > -101) {
					ob.bb[i4] = true;
					++i4;
				}
				
				oc.d = 0;
				sa.f = null;
				jh.e = null;
				i5 = 0;
				if (/*dummy != 0 || */~i5 > -7) {
					do {
						kg.d[i5] = new jg();
						++i5;
					} while (~i5 > -7);
				}
				
				i6 = 0;
				if (/*dummy != 0 || */~i6 > -26) {
					do {
						de.r[i6] = 0;
						gh.mb[i6] = 0;
						dg.Dc[i6] = 0;
						++i6;
					} while (~i6 > -26);
					
				}
			} else {
				while (~i1 > -5) {
					id = 0;
					int i7 = 0;
					while (true) {
						while (i7 < 104) {
							hf.C[i1][id][i7] = null;
							++i7;
						}
						
						++id;
						if (id >= 104) {
							break;
						}
						
						i7 = 0;
					}
					
					++i1;
				}
				
				vg.X = new pi();
				ch.bb = 0;
				ii.o = 0;
				int i8 = 0;
				while (wd.j > i8) {
					class_rd = qd.a(false, i8);
					if (class_rd != null && ~class_rd.H == -1) {
						ji.K[i8] = 0;
						sa.c[i8] = 0;
					}
					
					++i8;
				}
				
				int i7 = 0;
				while (b.fb.length > i7) {
					b.fb[i7] = -1;
					++i7;
				}
				
				if (bg.h != -1) {
					de.a(-3, bg.h);
				}
				
				class_re = (re) rd.J.b((byte) 117);
				while (class_re != null) {
					ba.a(class_re, var0 + 1, true);
					class_re = (re) rd.J.a((byte) -33);
				}
				
				bg.h = -1;
				rd.J = new md(8);
				sb.Z = null;
				si.S = 0;
				le.X = false;
				oe.g.a(new int[5], null, -1, 0, false);
				int i9 = 0;
				while (~i9 > -9) {
					gg.o[i9] = null;
					fh.c[i9] = false;
					++i9;
				}
				
				sh.c(32);
				o.d = true;
				int i10 = 0;
				while (~i10 > -101) {
					ob.bb[i10] = true;
					++i10;
				}
				
				oc.d = 0;
				sa.f = null;
				jh.e = null;
				int i11 = 0;
				while (~i11 > -7) {
					kg.d[i11] = new jg();
					++i11;
				}
				
				int i12 = 0;
				while (~i12 > -26) {
					de.r[i12] = 0;
					gh.mb[i12] = 0;
					dg.Dc[i12] = 0;
					++i12;
				}
			}
		} catch (RuntimeException var15) {
			throw bc.a(var15, "e.B(" + var0 + ')');
		}
	}
	
	static void a(byte paramByte) {
		int i9 = client.anInt_wb;
		try {
			pg.packetBuffer.initBITAccess((byte) 50);
			int i1 = pg.packetBuffer.readBits(8, 11339);
			System.out.println("Bit 8 = " + i1);
			if (tf.n > i1) {
				int i2 = i1;
				while ((~tf.n) < (~i2)) {
					ue.gb[(nf.S++)] = ud.Xb[i2];
					i2++;
				}
			}
			anInt_l += 1;
			if (i1 > tf.n) {
				throw new RuntimeException("gnpov1");
			}
			tf.n = 0;
			if (paramByte > -53) {
				a((byte) 78);
			}
			int i2 = 0;
			while ((~i1) < (~i2)) {
				int i3 = ud.Xb[i2];
				nb localnb = ai.M[i3];
				int i4 = pg.packetBuffer.readBits(1, 11339);
				System.out.println("NPCUPDATE - UpdateRequired: " + i4);
				if (i4 == 0) {
					ud.Xb[(tf.n++)] = i3;
					localnb.Ub = bi.f;
				} else {
					int i5 = pg.packetBuffer.readBits(2, 11339);
					if (i5 == 0) {
						ud.Xb[(tf.n++)] = i3;
						localnb.Ub = bi.f;
						mf.nb[(qf.I++)] = i3;
					} else {
						int i6;
						int i7;
						if ((~i5) == -2) {
							ud.Xb[(tf.n++)] = i3;
							localnb.Ub = bi.f;
							i6 = pg.packetBuffer.readBits(3, 11339);
							localnb.a(true, i6, false);
							i7 = pg.packetBuffer.readBits(1, 11339);
							if (i7 == 1) {
								mf.nb[(qf.I++)] = i3;
							}
						} else if (i5 == 2) {
							ud.Xb[(tf.n++)] = i3;
							localnb.Ub = bi.f;
							i6 = pg.packetBuffer.readBits(3, 11339);
							localnb.a(true, i6, true);
							i7 = pg.packetBuffer.readBits(3, 11339);
							localnb.a(true, i7, true);
							int i8 = pg.packetBuffer.readBits(1, 11339);
							if ((~i8) == -2) {
								mf.nb[(qf.I++)] = i3;
							}
						} else if (i5 == 3) {
							ue.gb[(nf.S++)] = i3;
						}
					}
				}
				i2++;
			}
		} catch (RuntimeException localRuntimeException) {
			throw bc.a(localRuntimeException, "e.A(" + paramByte + ')');
		}
		
	}
	
	public static void b(byte var0) {
		try {
			duelStake = null;
			k = null;
			j = null;
			ob_m = null;
			ob_n = null;
			i = null;
			of_h = null;
			if (var0 <= 22) {
				anInt_d = -77;
			}
			
			ints_b = null;
		} catch (RuntimeException var2) {
			throw bc.a(var2, "e.C(" + var0 + ')');
		}
	}
	
	static ob a(byte var0, ra var1) {
		try {
			if (var0 != -11) {
				return null;
			} else {
				++anInt_g;
				return fc.a(ce.a(var1, 18125), false) == 0 ? null : (var1.f != null && ~var1.f.d((int) 38).a(false) != -1 ? var1.f : (jh.j ? pe.W : null));
			}
		} catch (RuntimeException var3) {
			throw bc.a(var3, "e.D(" + var0 + ',' + (var1 != null ? "{...}" : "null") + ')');
		}
	}
	
	static {
		i = ob_m;
		j = rf.a(40, "Hier wechseln");
		anInt_d = 0;
	}
}
